# Generated by Django 3.0.6 on 2020-06-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER')], max_length=10)),
                ('order_amount', models.FloatField()),
                ('amount_collected', models.FloatField()),
                ('change_given', models.FloatField(blank=True, default=0, null=True)),
                ('change_outstanding', models.FloatField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
            ],
        ),
    ]
