# Generated by Django 3.0.6 on 2020-06-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('customer_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_age_bracket', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=10)),
                ('customer_added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_order_stat', models.BooleanField(default=False)),
                ('customer_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
