# Generated by Django 3.0.6 on 2020-06-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrugItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_man', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_size', models.CharField(blank=True, max_length=10, null=True)),
                ('drug_thumbnail', models.ImageField(blank=True, null=True, upload_to='drugs')),
                ('drug_composition', models.CharField(blank=True, max_length=200, null=True)),
                ('drug_stock', models.IntegerField()),
                ('drug_price', models.FloatField()),
                ('drug_mfd', models.DateField()),
                ('drug_exp', models.DateField()),
                ('drug_available_since', models.DateTimeField(auto_now_add=True)),
                ('drug_restocked_last', models.DateTimeField(auto_now=True)),
                ('drug_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.DrugCategory')),
            ],
        ),
    ]
